apiVersion : apps/v1
kind: Deployment
metadata:
  name: module10-replicas
  labels:
    app  : my-eks-app
    env  : prod
    owner: Raz_Orbach
spec:
  replicas: 4
  selector:
    matchLabels:
      project: pod-proj
  template:
    metadata:
      labels:
        project: pod-proj
    spec:
      containers:
        - name : nexus
          image: httpd:latest
          ports:
            - containerPort: 80
